### ISSUE TITLE
Install on (Arch) Linux

### ISSUE THREAD

**Issue by Tomaqa** [Kei18/mapf-visualizer#2]
The following steps worked for me on Arch Linux (while I suppose a situation where #1 was already fixed):

```
git clone --recurse_submodules https://github.com/Kei18/mapf-visualizer.git
cd mapf-visualizer/third_party/openFrameworks/scripts/linux/archlinux
sudo ./install_dependencies.sh
cd ..
./download_libs.sh
./compileOF.sh -j3
cd ../../../../
make
```

Not sure if running `compileOF.sh` is necessary (`make` itself also seems to compile stuff).

**Comment by Kei18** [comment]
Thank you for surveying 🙇  It's nice to know that.

In the future, I may make an install script for Linux.

**Comment by Tomaqa** [comment]
In the end, I managed to do the script (`install_linux.sh`), you can find it at my [fork](https://github.com/Tomaqa/mapf_r-visualizer), if you are interested.

However, it will require to use `sudo` to run `install_dependencies.sh` in your case, because I changed it in openFrameworks ..

**Comment by Kei18** [comment]
Wow, this is very helpful! Thanks!
