### ISSUE TITLE
Does the setup part needed to be modified in Ubuntu 24.04 version？

### ISSUE THREAD

**Issue by ShuaiZhou302** [Kei18/mapf-visualizer#8]
git clone https://github.com/Kei18/mapf-visualizer.git
cd mapf-visualizer
wget -O third_party/openFrameworks.tar.gz https://github.com/openframeworks/openFrameworks/releases/download/0.11.2/of_v0.11.2_linux64gcc6_release.tar.gz
tar -xzvf third_party/openFrameworks.tar.gz -C third_party --strip-components=1 --one-top-level=openFrameworks
sudo third_party/openFrameworks/scripts/linux/ubuntu/install_dependencies.sh
sudo third_party/openFrameworks/scripts/linux/ubuntu/install_codecs.sh
make -j4
echo "export PATH=$(pwd)/bin:\$PATH" >> ~/.bashrc

I run this setup on my ubuntu and most  passes but some error occur when setting up ros.

**Comment by Kei18** [comment]
Hi. Since Ubuntu 24.04 is new, there may be version issues. At least I never tested it myself.

Could you describe the errors you encountered in detail? It might also be worth trying different versions of openFrameworks:
https://github.com/openframeworks/openFrameworks/releases

Best,
Keisuke

**Comment by fengrn23** [comment]
！[上传截屏2024-06-04 15.01.53.png...]()hello,I installed it on my Mac, but when I input the command "mapf-visualizer assets/random-32-32-20.map assets/demo_random-32-32-20.txt " ,the terminal output"zsh: command not found: mapf-visualizer",what should I do? Thank you!

**Comment by JustinShetty** [comment]
Setup instructions were updated for Ubuntu 24 in #19
